site_name: PEH Validation Library
repo_url: https://github.com/eu-parc/peh-validation-library
repo_name: eu-parc/peh-validation-library
edit_uri: edit/master/docs/
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            show_root_toc_entry: true
            show_symbol_type_heading: true
            allow_inspection: true
            parameter_headings: true
            heading_level: 2
            show_source: true
            docstring_style: google
            docstring_section_style: table
            show_docstring_examples: true
            annotations_path: source
            separate_signature: true
            line_length: 60
            show_signature: true
            show_signature_annotations: true
