name: DOCS

on:
  pull_request:
    branches: [master]
    types:
      - closed

permissions:
  contents: write
  pages: write  
  id-token: write  
  actions: write

jobs:
  docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.13"

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
    
    - uses: actions/cache@v4
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache 
        restore-keys: |
          mkdocs-material-
    
    - name: Install dependencies
      run: uv sync --locked --only-group docs

    - name: Run docs build
      run: bash ./scripts/docs_build.sh